module: nopod

replicas: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true  # Changed from 'enable' to 'enabled' for consistency
  metadata:
    annotations:
      pathRewrite: /
  # tls:
  #   enabled: true
  #   annotations:
  #     cert-manager.io/cluster-issuer: "letsencrypt-prod"
  # host: myhost  # Moved this out of 'hosts' array for simplicity
  spec:
    path: /
    pathType: Prefix