module: pods-manager

replicas: 1


containers:
  image: ghcr.io/miletocarmelo/pods-manager
  name: python-frontend  # This should match the name in your deployment template
  tags: latest
  ports:
    containerPort: http # This should be the port your app listens on (http : 80, https : 443)

service:
  type: ClusterIP
  port: http
  targetPort: http

ingress:
  enabled: true  # Changed from 'enable' to 'enabled' for consistency
  metadata:
    annotations:
      pathRewrite: /
  # tls:
  #   enabled: true
  #   annotations:
  #     cert-manager.io/cluster-issuer: "letsencrypt-prod"
  # host: myhost  # Moved this out of 'hosts' array for simplicity
  spec:
    path: /
    pathType: Prefix