apiVersion: v1
entries:
  generic-python-frontend:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2024-10-21T19:04:52.859074661+02:00"
    description: A Helm chart for kubernetes - Generic python frontend
    digest: e3b4bb308935c9d30808becb1952ba1e3bfacf7e6e338e235a4179812d179779
    name: generic-python-frontend
    type: application
    urls:
    - https://raw.githubusercontent.com/MiletoCarmelo/DEVOPS_HELM_generic_python_frontend/github-pages/charts/generic-python-frontend-0.1.0.tgz
    version: 0.1.0
generated: "2024-10-21T19:04:52.85855949+02:00"
