environment: prod
module: trading-strategy-analysis-prod

prod:
  enabled: true
dev:
  enabled: false

replicas: 1

technicalSecret: true

containers:
  name: frontend  # This should match the name in your deployment template
  image: ghcr.io/miletocarmelo/pods-manager
  tags: latest
  ports:
    containerPort: 80
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "200m"

service:
  port: 80
  targetPort: http

ingress:
  enabled: true  # Changed from 'enable' to 'enabled' for consistency
  annotations:
    kubernetes.io/ingress.class: nginx  # Added this common annotation
    nginx.ingress.kubernetes.io/rewrite-target: /  # Changed from pathRewrite
  tls:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
  host: myhost  # Moved this out of 'hosts' array for simplicity
  path: /
  pathType: Prefix

# Commented out sections are removed as they're not currently used
# dynamicPod:
#   instanceSuffix: "1"
# podManager:
#   image: ghcr.io/miletocarmelo/pods-manager
#   tag: latest