module: trading-strategy-analysis-prod

environment: prod  # Default to prod, override in values-prod.yaml

replicas: 1
# if set to 0 , the pod will not be created during the deployment

technicalSecret: true

containers:
  image: ghcr.io/miletocarmelo/pods-manager
  name: frontend
  tags: latest
  ports:
    containerPort: 80
  resources:
    requests:
      memory: "512Mi"  # Updated memory request
      cpu: "200m"
    limits:
      memory: "1024Mi"  # Updated memory limit
      cpu: "200m"

service:
   port: 80 # doit etre identique à celui contenu dans le fichier service.yaml
            # Optional, will use named port "http" if not specified

ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
  tls:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"

  hosts:
    - host: myhost  # Change to your desired host
      paths:
        - path: /
          pathType: Prefix

  spec:
    path: /
    pathType: Prefix


# dynamicPod:
#   instanceSuffix: "1"  # Changez ceci pour générer des noms uniques pour vos pods

# podManager:
#      image: ghcr.io/MiletoCarmelo/build-push-image-pods-management-prod
#      tag: latest