apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trading-strategy-analysis-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MiletoCarmelo/DEVOPS_HELM_generic_python_frontend
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true