apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.module }}-{{ .Values.environment }}-deployment
  labels:
    {{- include "label-generator" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.module }}-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.module }}-{{ .Values.environment }}
        {{- include "label-generator" . | nindent 8 }}
    spec:
      {{- if .Values.technicalSecret }}
      imagePullSecrets:
        - name: technical-secret
      {{- end }}
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tags }}
          {{- if hasSuffix "latest" .Values.containers.tags }}
          imagePullPolicy: Always
          {{- else }}
          imagePullPolicy: IfNotPresent
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containers.ports.containerPort }}
          {{- if .Values.containers.resources }}
          resources:
            {{- toYaml .Values.containers.resources | nindent 12 }}
          {{- end }}