apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{-  include "label-generator" . | nindent 4 }}
    module: {{ .Values.module }}
  name: {{ .Values.environment }}-{{ .Values.module }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.environment }}-{{ .Values.module }}-pod
  template:
    metadata:
      labels:
        app: {{ .Values.environment }}-{{ .Values.module }}-pod
    spec:
{{- if .Values.technicalSecret }}
      imagePullSecrets:
        - name: technical-secret
{{- end}}
{{- if .Values.containers }}
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tags }}
{{- if hasSuffix "latest" .Values.containers.tags }}
          imagePullPolicy: Always
{{- else }}
          imagePullPolicy: IfNotPresent
{{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.containers.ports.containerPort }} # Cela doit être le port que votre app écoute
{{- if .Values.containers.resources }}
          resources:
            requests:
              memory: {{ .Values.containers.resources.requests.memory }}
              cpu: {{ .Values.containers.resources.requests.cpu }}
            limits:
              memory: {{ .Values.containers.resources.limits.memory  }}
              cpu: {{  .Values.containers.resources.limits.cpu }}
{{- end }}
{{- end }}
