name: Pods Management Images - Prod

on:
  push:
    branches: 
      - prod

env:
  REGISTRY_NAME: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  # IMAGE_NAME: ${{ github.repository }}/build-push-image-pods-management-prod
  IMAGE_NAME: ${{ github.repository_owner }}/pods-manager
  IMAGE_TAG: latest

permissions:
  contents: write  # Allows reading files from the repository
  packages: write  # Allows pushing images to the GitHub Container Registry

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Pull main branch
      run: git pull origin main

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_NAME }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}

    - name: Set lowercase IMAGE_NAME
      id: set_image_name
      run: echo "IMAGE_NAME_LOWER=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push prod image
      uses: docker/build-push-action@v6
      with:
        context: ./charts/prod/scripts
        file: ./charts/prod/scripts/Dockerfile
        push: true
        tags: ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME_LOWER }}:${{ env.IMAGE_TAG }}

    - name: Update prod Kubernetes resources
      run: |
        sed -i 's|image:.*|image: ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME_LOWER }}|' charts/prod/values.yaml
        sed -i 's|tag:.*|tag: ${{ env.IMAGE_TAG }}|' charts/prod/values.yaml

    - name: Set user for git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Commit
      run: |
        git add charts/prod/values.yaml 
        git commit -m "Update image tags for pods management" || echo "No changes to commit"
          
    - name: Push to prod
      run: |
        git push origin HEAD:main
