name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Helm Package
        run: |
          helm package .
          mkdir -p .cr-release-packages
          mv *.tgz .cr-release-packages/

      - name: Upload chart package
        uses: actions/upload-artifact@v3
        with:
          name: helm-chart
          path: .cr-release-packages/*.tgz

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: github-pages
          clean: true
          fetch-depth: 0

      - name: Download chart package
        uses: actions/download-artifact@v3
        with:
          name: helm-chart

      - name: Generate Helm repository index
        run: |
          helm repo index . --url https://raw.githubusercontent.com/${{ github.repository }}/github-pages

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update Helm chart repository"
          git push origin github-pages